### ISSUE TITLE
null pointer from using RestAdapter

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-sdk-android#101]
I got this when I start using the `RestAdapter` at `oncreate` in the activity.

07-22 17:10:27.423 14026-14026/tileview.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: tileview.demo, PID: 14026
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{****}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.loopj.android.http.AsyncHttpClient.addHeader(java.lang.String, java.lang.String)' on a null object reference
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.loopj.android.http.AsyncHttpClient.addHeader(java.lang.String, java.lang.String)' on a null object reference
                                                                   at com.strongloop.android.loopback.RestAdapter.setAccessToken(RestAdapter.java:32)
                                                                   at com.strongloop.android.loopback.RestAdapter.<init>(RestAdapter.java:27)
                                                                   at com.galleria.loopbackdataclip.GalleriaLB.init(GalleriaLB.java:101)
                                                                   at com.galleria.loopbackdataclip.GalleriaLB.getInstance(GalleriaLB.java:57)
                                                                   at tileview.demo.NetworkMap.onCreate(NetworkMap.java:38)
                                                                   at android.app.Activity.performCreate(Activity.java:6251)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by serjooo** [comment]
How are you creating the RestAdapter can we see some code?
